server:
  port: 8080

spring:
  datasource:
    username:  root
    password: 123456
    url: jdbc:mysql://192.168.1.103/hancloud_pf_web?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#&serverTimezone=UTC
#扫描映射文件
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml


logging:
  level:
   com.jscloud: debug